### ISSUE TITLE
Build lua modules mnist and ann with lua 5.4

### ISSUE THREAD

**Issue by Mexico-zyy-lost** [cloudwu/neuralnet#1]
hi ,how to do this step?i'm fish here

**Comment by cloudwu** [comment]
Windows/Mingw :

1. Use pacman to Install gcc and gnu make 
2. Download lua 5.4.4 source code from https://www.lua.org/, and build it.
3. make

**Comment by Mexico-zyy-lost** [comment]
tks,bro

**Comment by nough1** [comment]
mac envrironment , how to do this step success , it seems can not find lua54 lib

**Comment by cloudwu** [comment]
download lua source code from https://www.lua.org/ , and build it.

**Comment by kardusenor** [comment]
> download lua source code from [lua.org](https://www.lua.org/) , and build it.

Hello,

I am trying to run the network.lua script after downloading the MNIST data from http://yann.lecun.com/exdb/mnist/ and putting it into the data/ directory, and building the mnist and ann modules with Lua 5.4. However, I am encountering an error that says “dynamic libraries not enabled; check your Lua installation.”

I have searched online for solutions but have not found any information on how to resolve this issue. Could you please provide guidance on how to properly install Lua to avoid this issue?

Thank you.

**Comment by cloudwu** [comment]
https://web.tecgraf.puc-rio.br/~lhf/ftp/lua/install.html
